services:
  python-server:
    build:
      context: ./python-server
    ports:
      - "8000:8000"
    volumes:
      - ./python-server:/app
    command: ["uvicorn", "src.main:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]

  js-express-server:
    build:
      context: ./js-express-server
    ports:
      - "8001:8001"
    volumes:
      - ./js-express-server:/app
      - /app/node_modules
    command: ["yarn", "dev"]
